### ISSUE TITLE
[Proposal]: Improvements to 5G SA Access Function for Reliability, Maintainability and extensibility

### ISSUE THREAD

**Issue by panyogesh** [magma/grants#15]
## Elevator Pitch

Access side of the magma 5G SA system is expected to meet the reliability demands of operators and enterprises. With every 3GPP release supported on magma, cost of software development is to be optimal. This is possible when system is designed for extensibility and has very minimal modifications. Also, 5G SA core is also expected to address the non functional requirements compiled by TIP. Current proposal   addresses some of these requirements by re-designing portions of AMF for better efficiency and optimization.

## Total ask

Improving the 5G SA access procedures and data structures will be delivered in roughly 6 Milestones.

## Contact Information

Yogesh Pandey (yogesh@wavelabs.ai)

## Project Details

Following are the summary of changes :
- Enhancing the NAS5G library to be make use of object oriented approach and new features available in latest C++ libraries with well defined objects and clearly established relations. Bring uniformity across all encoding/decoding classes along with buffer management.

- Optimizing procedure handling logic and state machine making it more robust for expected transitions, failures, timeout handlings etc. Improve the performance numbers.

- Introduce additional counters for debugging purpose to track of all state transitions targeting for production system.

- Introducing CLI framework for AMF to fetch counters and ue context snapshot as required. Required for load & performance of the Appliance is benchmarked.  

- Enhance the unit testing infrastructure making it flexible to take any frame sequence and also making use of advanced gmock features for the verification.

## Delivery Approach
Scope of this proposal will be delivered in 6 milestones. Each milestone will have the following 5 process gates 
1. Design
2. Development & Unit Testing 
3. code review
4. regression testing 
5. resolve all regression issues Before finishing the last milestone.  

### Milestone1 - NAS5G library Enhancements
 
- Re-align the packet message structure identifying the objects and relationships along with mandatory and optional fields
- Shape up a  consistent buffer mechanism both for encoding and decoding with validation infrastructure
- Process all the optional fields as per 3GPP spec 24.501 V15.8

### Milestone2 - Optimization of existing  procedures and state machine 

- Amf procedure structure to be flattened with only 2 level hierarchy and simplified fields
- Flatten the hierarchy in various procedures (target is to have only 2 levels of hierarchy like Procedures : Registration -> Security Mode)
- State Machine to be imbibed into the ue_context infrastructure.
- State Machine to have a clear transition map defined (success, failure, timeout)
- Improving the scalability and performance number target for 1200 UEs

### Milestone3 - Enhancing the unit testing infrastructure

- To make the unit test infrastructure more flexible in terms of frame or sequence of packet selection.
- To use extended functionality of Gmock framework for validation.
- Possible extensions to decode the packet sent towards NGAP and do more field level validation. 
- Extend the coverage for the few more negative scenarios
- Improving the overall Unit testing coverage targeting

### Milestone4 - Additional Debug counters and CLI infrastructure for AMF

Task specific to counters
- Adding the critical counters to trace the current state (like amf_context, session context etc) 
- Displaying the counters at regular intervals including connected ues, gnb etc.

Task specific to CLI infrastructure
- Python based CLI layer for AMF
- Interfacing with grpc handler and eventually landing on to itti_message infrastructure of AMF
- Targeting to have counter level information for debugging purpose.
- Any critical data structure related information to be fetched as required.

### Milestone5 - Code profiling 
- Creating a code profiling infrastructure to see the time spend on the critical functions.
- Creating the call flow graph and time spent overall.
- Tuning based on the output from the tool.

## Test Plan

Following are the test tools to be used for the overall project

### Integration Testing using UERANSIM or equivalent simulator

- For dev testing UERANSIM or equivalent simulator will be used.
- Covering all Mobility Management, Session Management procedures
- Traffic Testing scenarios
- All regression and scale testing to be covered.
- Additional automation testcases to be added.

## Roadmap

Feature will be delivered in 5 Milestones. Each milestone duration is 45 calendar days. 

###
--------------------------------------------------------------------------------------------------------------------------
|Milestone    |             Deliverable Summary                                                               |  |  
|-------------|-----------------------------------------------------------------------------------------------|----------| 
| M1.0		  | MME(AMF/NGAP)		 NAS5G library Enahncements                                               |  |                                         
| M2.0		  | MME(AMF/NGAP)        Optimisations to procedures and state machine                            |  |
| M4.0		  | MME(AMF/NGAP)        Enhancing the unit testing infrastructure                                |  |
| M5.0        | MME(AMF/NGAP)        Additional Debug counters and CLI infrastructure                         |   |
| M6.0        | MME(AMF/NGAP)        create profiling  and fix issues to optimize call flow graph         |  |  

## References

- https://app.zenhub.com/workspaces/magma-5fac75d3e2cd890011f1677a/issues/magma/magma/9721
- https://github.com/magma/magma/issues/10810
- https://github.com/google/benchmark
- https://www.etsi.org/deliver/etsi_ts/124500_124599/124501/15.03.00_60/ts_124501v150300p.pdf
- https://www.etsi.org/deliver/etsi_ts/123500_123599/123502/15.04.01_60/ts_123502v150401p.pdf

**Comment by wendallkaters** [comment]
Thank you for submitting this proposal. The MCF grant program is devoted to “kickstarting” sustainable, Magma-powered commercial products and businesses. The MCF Governing Board will prioritize proposals that are directly linked to deals or a sales pipeline. While the technical and feature work is clearly defined, we are unable to prioritize this proposal without clear revenue opportunities.
