### ISSUE TITLE
[Proposal]: To support Mobile Initiated Connection Only(MICO) Mode

### ISSUE THREAD

**Issue by Kaleem-Wavelabs** [magma/grants#17]
## Overview & Purpose
Some of the IOT devices require uplink only mode. It means device only will initiate radio connection when it has some data to deliver. 3GPP TS 123.501 defines a new connection mode known as Mobile Initiated Connection Only (MICO) mode. When a MICO activated device is in an Idle state, the magma core network needs to consider the device is unreachable. Transition to Connected state will always be triggered by device.  The device will not be paged whilst in MICO mode. MICO mode does not apply to non-3GPP access.

## Scope of Work
• MICO is a mode of operation for 5G only devices, connected to 5G Core (5GC), does not apply to non-3GPP access. A device can request the AMF to enable MICO mode. When a MICO activated device is in an Idle state, the 5G network will consider the device to be unreachable.

• The device will only receive MT (Mobile Terminated) data when it transitions to a Connected state.

• The AMF shall include the MICO indication IE in the REGISTRATION ACCEPT message only if the MICO
indication IE was included in the REGISTRATION REQUEST message to indicate that the AMF supports and accepts the use of
MICO mode. 

• When AMF indicates MICO mode to a UE, the AMF considers the UE always unreachable while the UE CM state in the AMF is CM-IDLE. AMF rejects any request for downlink data delivery for UE in MICO mode and whose UE CM state is CM-IDLE with an appropriate cause.

• While performing registration with the MICO mode, AMF assigns "all PLMN registration area allocated" in the MICO indication IE in the REGISTRATION ACCEPT message to the UE because network can't perform any signalling towards such kind of UE and there is no optimization required in that context compare to the LTE core network which performs many optimization schemes for tracking area management

• If the UE is not registered for emergency services and Timer is set in the REGISTRATION REQUEST message to activate MICO mode for the UE, AMF includes timer T3324 in the REGISTRATION ACCEPT message in response to UE.  

• AMF does not know for how long the UE remains not reachable, thus the AMF shall not immediately de-register the UE. Instead, after the expiry of the Mobile Reachable timer, the AMF will clear the PPF and shall start an Implicit De-registration timer, with a relatively large value. The AMF shall stop the Implicit De-registration timer and set the PPF if the AMF moves the UE CM state in the AMF to CM-CONNECTED state.

## Delivery Approach
Feature will be delivered in 2 milestones. Each milestone will have the following 5 process gates
1. Design
2. Development & Unit Testing
3. code review 
4. Integration testing
5. resolve integration issues and regression issues

Before finishing the 2nd milestone, the feature shall pass the following process gates 
6. System test
7. User Acceptance test

### Milestone1

Tasks to be handled on AMF
1. Support for additional IEs in REGISTRATION REQUEST and REGISTRATION ACCEPT messages.
2. Support for active timer and Implicit De-registration timer.

Unit tests will be added for all new functions introduced.

### Milestone2

Tasks to be handled on magma SMF and UPF
1. Notification from AMF to SMF to mark the PDU sessions with MICO mode.
2. Notification from SMF to UPF to mark the PDU sessions with MICO mode.
3. Disabling NAS signaling and data traffic during idle mode for MICO mode devices.
4. Disabling paging notifications during MICO mode.

Unit tests will be added for all new functions introduced. 

## Test Plan
 
Following is the set of test scenarios to verify MICO mode Support.

1. Testing of new timers implementation. 
    a) Active timer 
        - Cause of start, when entering 5GMM-IDLE mode after indicating MICO mode activation to the UE with an active timer value
        - On expiry, activate MICO mode for the UE.
    b) Implicit De-registration timer
        - Cause of start, entering 5GMM-IDLE mode over 3GPP access if the MICO mode is activated and strictly periodic monitoring timer is not running.
        - On expiry, implicitly de-register the UE on 1st expiry.
2. End to end traffic testing with activation of MICO mode covering all the scenarios.

## Feature Roadmap

Feature will be delivered in 2 Milestones. 

-------------------------------------------------------------------------------------------------------------
|Milestone    |             Deliverable Summary                                                                             
|-------------|----------------------------------------------------------------------------------------------- 
|MS1          | Magma AMF support						                                                  
|MS2          | Magma SMF, UPF support and integration test                                                   

## References
1) https://www.etsi.org/deliver/etsi_ts/123500_123599/123501/15.03.00_60/ts_123501v150300p.pdf
2) https://blog.3g4g.co.uk/2020/07/mobile-initiated-connection-only-mico.html
3) https://itectec.com/spec/5-4-3gpp-access-specific-aspects/

**Comment by wendallkaters** [comment]
Thank you for submitting this proposal. The MCF grant program is devoted to “kickstarting” sustainable, Magma-powered commercial products and businesses. The MCF Governing Board will prioritize proposals that are directly linked to deals or a sales pipeline. While the technical and feature work is clearly defined, we are unable to prioritize this proposal without clear revenue opportunities.
